# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            João Miranda's blog
tagline:          But I digress...
url:              http://jhosm.github.io
paginate:         1
baseurl:          /
author:
  name:           João Miranda
  url:            https://twitter.com/jhosm
  email:          joao.hugo.miranda @ gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/jhosm/jhosm.github.io

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
